development: &default
  adapter: postgresql
  encoding: unicode
  database: defence_of_data_development
  pool: 20
  host: localhost
  port: 5432

test:
  <<: *default
  database: defence_of_data_test

production:
